const ADD_MESSAGE = 'ADD_MESSAGE';
const DELETE_MESSAGE = 'DELETE_MESSAGE';
const EDIT_MESSAGE = 'EDIT_MESSAGE';
const SET_MESSAGES = 'SET_MESSAGES';

export {
  ADD_MESSAGE,
  DELETE_MESSAGE,
  EDIT_MESSAGE,
  SET_MESSAGES
}